// import localFont from "next/font/local";
import { Poppins, Manrope } from 'next/font/google';
import { AuthProvider } from '@/contexts/AuthContext';
// import {
//   useQuery,
//   useMutation,
//   useQueryClient,
//   QueryClient,
//   QueryClientProvider,
// } from '@tanstack/react-query';
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-manrope',
  weight: [ '200', '300', '400', '500', '600', '700', '800']
});

export const metadata = {
  title: "Nexus Mall",
  description: "Generated by create next app",
  icons: {
    icon: 'public/static/images/favicon.ico', // /public path
  },
};

// const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${manrope.variable} antialiased`}
      >
        <div>
        <AuthProvider>
        {children}
        </AuthProvider>
        
        </div>
      </body>
    </html>
  );
}
